### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by terencebeh** [ROBOTIS-GIT/open_manipulator_controls#2] opened 2020-04-08 15:21 UTC
I execute the following 3 statements: 
```
cd ~/catkin_ws/src/
git clone https://github.com/ROBOTIS-GIT/open_manipulator_controls.git
cd ~/catkin_ws && catkin_make

```

Output the following error: 

```
...@ubuntu16-robotics:~/catkin_ws$` cd ~/catkin_ws && catkin_make
Base path: /home/.../catkin_ws
Source space: /home/.../catkin_ws/src
Build space: /home/.../catkin_ws/build
Devel space: /home/.../catkin_ws/devel
Install space: /home/.../catkin_ws/install
####
#### Running command: "make cmake_check_build_system" in "/home/.../catkin_ws/build"
####
-- Using CATKIN_DEVEL_PREFIX: /home/.../catkin_ws/devel
-- Using CMAKE_PREFIX_PATH: /opt/ros/kinetic
-- This workspace overlays: /opt/ros/kinetic
-- Found PythonInterp: /usr/bin/python2 (found suitable version "2.7.12", minimum required is "2") 
-- Using PYTHON_EXECUTABLE: /usr/bin/python2
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/.../catkin_ws/build/test_results
-- Found gtest sources under '/usr/src/gmock': gtests will be built
-- Found gmock sources under '/usr/src/gmock': gmock will be built
-- Found PythonInterp: /usr/bin/python2 (found version "2.7.12") 
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.7.20
-- BUILD_SHARED_LIBS is on
-- BUILD_SHARED_LIBS is on
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- ~~  traversing 17 packages in topological order:
-- ~~  - open_manipulator_controls (metapackage)
-- ~~  - open_manipulator_moveit_config
-- ~~  - open_manipulator_simulations (metapackage)
-- ~~  - turtlebot3 (metapackage)
-- ~~  - turtlebot3_msgs
-- ~~  - turtlebot3_navigation
-- ~~  - dynamixel_sdk
-- ~~  - robotis_manipulator
-- ~~  - open_manipulator_hw
-- ~~  - roboticsgroup_gazebo_plugins
-- ~~  - turtlebot3_bringup
-- ~~  - turtlebot3_example
-- ~~  - turtlebot3_slam
-- ~~  - turtlebot3_teleop
-- ~~  - open_manipulator_controllers
-- ~~  - open_manipulator_gazebo
-- ~~  - turtlebot3_description
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- +++ processing catkin metapackage: 'open_manipulator_controls'
-- ==> add_subdirectory(open_manipulator_controls/open_manipulator_controls)
-- +++ processing catkin package: 'open_manipulator_moveit_config'
-- ==> add_subdirectory(open_manipulator_controls/open_manipulator_moveit_config)
-- +++ processing catkin metapackage: 'open_manipulator_simulations'
-- ==> add_subdirectory(open_manipulator_simulations/open_manipulator_simulations)
-- +++ processing catkin metapackage: 'turtlebot3'
-- ==> add_subdirectory(turtlebot3/turtlebot3)
-- +++ processing catkin package: 'turtlebot3_msgs'
-- ==> add_subdirectory(turtlebot3_msgs)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- turtlebot3_msgs: 3 messages, 0 services
-- +++ processing catkin package: 'turtlebot3_navigation'
-- ==> add_subdirectory(turtlebot3/turtlebot3_navigation)
-- +++ processing catkin package: 'dynamixel_sdk'
-- ==> add_subdirectory(DynamixelSDK/ros)
-- +++ processing catkin package: 'robotis_manipulator'
-- ==> add_subdirectory(robotis_manipulator)
-- +++ processing catkin package: 'open_manipulator_hw'
-- ==> add_subdirectory(open_manipulator_controls/open_manipulator_hw)
CMake Warning at /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:76 (find_package):
  Could not find a package configuration file provided by
  "dynamixel_workbench_toolbox" with any of the following names:

    dynamixel_workbench_toolboxConfig.cmake
    dynamixel_workbench_toolbox-config.cmake

  Add the installation prefix of "dynamixel_workbench_toolbox" to
  CMAKE_PREFIX_PATH or set "dynamixel_workbench_toolbox_DIR" to a directory
  containing one of the above files.  If "dynamixel_workbench_toolbox"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  open_manipulator_controls/open_manipulator_hw/CMakeLists.txt:12 (find_package)


-- Could not find the required component 'dynamixel_workbench_toolbox'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
CMake Error at /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by
  "dynamixel_workbench_toolbox" with any of the following names:

    dynamixel_workbench_toolboxConfig.cmake
    dynamixel_workbench_toolbox-config.cmake

  Add the installation prefix of "dynamixel_workbench_toolbox" to
  CMAKE_PREFIX_PATH or set "dynamixel_workbench_toolbox_DIR" to a directory
  containing one of the above files.  If "dynamixel_workbench_toolbox"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  open_manipulator_controls/open_manipulator_hw/CMakeLists.txt:12 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/.../catkin_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/.../catkin_ws/build/CMakeFiles/CMakeError.log".
Makefile:2250: recipe for target 'cmake_check_build_system' failed
make: *** [cmake_check_build_system] Error 1
Invoking "make cmake_check_build_system" failed
...@ubuntu16-robotics:~/catkin_ws$ 
```

I appreciate your help.

**Comment by JaehyunShim** [comment] 2020-05-22 05:08
@terencebeh 

Duplicate of [link](https://github.com/ROBOTIS-GIT/open_manipulator_controls/issues/1#issue-591936552).

Ryan

**Closed as completed by JaehyunShim** 2020-05-22 05:08 UTC
